[build]
  command = "bash netlify-build.sh"
  publish = "dist"
  
# Si Expo crea web-build, lo renombramos a dist en el script

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/debug.html"
  status = 200
